### ISSUE TITLE
Enable a General Conversation with Health Records

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/LLMonFHIR#22]
### Use Case

It would be good if users can have a general conversation with LLM on FHIR that includes all possible FHIR resources in the conversation and requests additional context based on the questions asked by the user.

### Problem

The current LLMonFHIR implementation only works with a single FHIR resource that is investigated in the detail screen.

Having a conversation with the complete history of health records is essential to identify context shared across multiple resources.

### Solution

The implementation should provide the model with an overview of all collected Health records and a short summary for each record.

We can use the [function calling API](https://platform.openai.com/docs/guides/gpt/function-calling) in the OpenAI interface to enable a structured interaction with the LLM to request additional data and provide it back to the conversation flow.

We should explore the functionality to query data added to the conversation in the context of https://github.com/StanfordSpezi/SpeziML/issues/10 to include the [function calling API](https://platform.openai.com/docs/guides/gpt/function-calling) of OpenAI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by gamingflexer** [comment]
Hey i tried building it on my ipad, it crashes as Apple Health is not available for Ipad.

General chat would be great !

**Comment by PSchmiedmayer** [comment]
Closed by different PRs by @AdritRao & @PSchmiedmayer 🚀
