### ISSUE TITLE
Provide an Optional Chat History

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/LLMonFHIR#24]
### Problem

Any conversations currently made with the LLMonFHIR application are not saved.

### Solution

We should add a nice UI to access chat history and potentially resume a chat.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by philippzagar** [comment]
As of https://github.com/StanfordBDHG/LLMonFHIR/pull/44, the chat history is stored via the SpeziStorage model and accessible even after the application is closed.
